const { getSubjectLineRuntimeConfig } = require('../config/subjectLineRuntime');
const { AI_EVENT_TYPES, logAiEvent } = require('../logging/aiStructuredLogger');
const { parseJsonLoose } = require('../parsers/jsonResponse');
const { parseSubjectResponseToNormalized } = require('../parsers/subjectResponse.parser');
const { validateNormalizedSubjects } = require('../validators/subjectOutput.validator');
const { fetchSubjectLineJson } = require('../providers/subjectLineHttp.provider');
const { buildPipelineStubResponseJson } = require('../providers/pipelineStubJson');
const {
  buildFallbackSubjectLines,
  ensureExactlyFive,
  buildEffectiveBrief,
} = require('../subject-lines/subjectLineShared');
const { assertModuleEnabled } = require('../modules/aiModuleRegistry');

/**
 * @typedef {object} SubjectLineGenHooks
 * @property {(entry: Record<string, unknown>) => Promise<void>} [persistLog]
 */

/**
 * @typedef {object} BriefModeInput
 * @property {'brief'} mode
 * @property {string} effectiveBrief
 * @property {string} tone
 * @property {string} prompt
 */

/**
 * @typedef {object} PipelineModeInput
 * @property {'pipeline'} mode
 * @property {string} prompt
 * @property {Record<string, unknown>} ctx
 * @property {string} emailBody
 */

/**
 * Convert canonical subjects (0–1 score) to legacy API rows (1–10 scores).
 * @param {Array<{ text: string, score: number, style?: string, reason?: string }>} subjects
 */
function subjectsToLegacyRows(subjects) {
  return subjects.map((s, idx) => {
    const score10 = Math.min(10, Math.max(1, Math.round(s.score <= 1 ? s.score * 10 : s.score)));
    return {
      style: s.style?.trim() || ['Curiosity', 'Urgency', 'Personalized', 'Question-based', 'Short'][idx] || 'General',
      subject: s.text,
      score: score10,
      reason: s.reason?.trim() || 'Generated by AI',
    };
  });
}

/**
 * @param {BriefModeInput | PipelineModeInput} input
 * @param {object} ctx
 * @param {string} ctx.traceId
 * @param {string} [ctx.requestId]
 * @param {string} [ctx.jobId]
 * @param {string} [ctx.userId]
 * @param {string} [ctx.organizationId]
 * @param {string} [ctx.campaignId]
 * @param {SubjectLineGenHooks} [hooks]
 */
async function runSubjectLineGeneration(input, ctx, hooks) {
  const config = getSubjectLineRuntimeConfig();
  const started = Date.now();
  let retryCount = 0;
  /** @type {string[]} */
  const retryReasons = [];

  try {
    assertModuleEnabled('subjectLines');
  } catch (e) {
    logAiEvent({
      eventType: AI_EVENT_TYPES.GENERATION_FAILED,
      status: 'disabled',
      traceId: ctx.traceId,
      requestId: ctx.requestId,
      jobId: ctx.jobId,
      isProduction: config.environment === 'production',
      extra: { message: 'Feature flag AI_FEATURE_SUBJECT_LINES=0' },
    });
    throw e;
  }

  logAiEvent({
    eventType: AI_EVENT_TYPES.REQUEST_RECEIVED,
    status: 'ok',
    traceId: ctx.traceId,
    requestId: ctx.requestId,
    jobId: ctx.jobId,
    isProduction: config.environment === 'production',
    extra: { mode: input.mode },
  });

  logAiEvent({
    eventType: AI_EVENT_TYPES.GENERATION_STARTED,
    status: 'ok',
    traceId: ctx.traceId,
    requestId: ctx.requestId,
    jobId: ctx.jobId,
    provider: 'http',
    isProduction: config.environment === 'production',
  });

  /** @type {Array<{ text: string, score: number, style?: string, reason?: string }>} */
  let merged = [];
  let usedFallback = false;
  let lastInvalidReasons = /** @type {string[]} */ ([]);

  for (let attempt = 0; attempt < config.maxGenerationAttempts && merged.length < config.expectedSubjectCount; attempt += 1) {
    /** @type {string | null} */
    let rawText = null;

    // eslint-disable-next-line no-await-in-loop
    const httpResult = await fetchSubjectLineJson(input.prompt, {
      timeoutMs: config.providerTimeoutMs,
      networkMaxAttempts: config.networkMaxAttempts,
      retryBaseMs: config.retryBaseMs,
      retryMaxMs: config.retryMaxMs,
    });

    if (httpResult.skipped && input.mode === 'brief') {
      logAiEvent({
        eventType: AI_EVENT_TYPES.FALLBACK_USED,
        status: 'ok',
        traceId: ctx.traceId,
        requestId: ctx.requestId,
        jobId: ctx.jobId,
        provider: 'none',
        isProduction: config.environment === 'production',
        extra: { reason: 'PROVIDER_NOT_CONFIGURED', note: 'brief_mode_local_fallback' },
      });
      break;
    }

    if (httpResult.ok && httpResult.rawText) {
      rawText = httpResult.rawText;
    } else if (httpResult.skipped && input.mode === 'pipeline') {
      rawText = buildPipelineStubResponseJson(input.ctx, input.emailBody);
      usedFallback = true;
      logAiEvent({
        eventType: AI_EVENT_TYPES.FALLBACK_USED,
        status: 'ok',
        traceId: ctx.traceId,
        requestId: ctx.requestId,
        jobId: ctx.jobId,
        provider: 'stub',
        isProduction: config.environment === 'production',
        extra: { reason: 'PROVIDER_NOT_CONFIGURED' },
      });
    } else if (!httpResult.ok) {
      retryCount += 1;
      retryReasons.push(httpResult.errorCode || 'PROVIDER_FAILED');
      logAiEvent({
        eventType: AI_EVENT_TYPES.RETRY_TRIGGERED,
        status: 'retry',
        traceId: ctx.traceId,
        requestId: ctx.requestId,
        jobId: ctx.jobId,
        provider: 'http',
        retryCount,
        retryReason: httpResult.errorCode,
        isProduction: config.environment === 'production',
      });
      if (attempt + 1 >= config.maxGenerationAttempts) break;
      // eslint-disable-next-line no-await-in-loop
      await new Promise((r) => {
        setTimeout(r, Math.min(config.retryMaxMs, config.retryBaseMs * 2 ** attempt));
      });
      continue;
    }

    try {
      if (!rawText) {
        throw new Error('EMPTY_RAW');
      }
      const parsed = parseJsonLoose(rawText);
      const normalized = parseSubjectResponseToNormalized(parsed);
      const validation = validateNormalizedSubjects(normalized, {
        maxPerLine: config.maxSubjectLength,
        minCount: 1,
        maxCount: Math.max(config.expectedSubjectCount, 20),
      });
      if (!validation.ok) {
        lastInvalidReasons = validation.errors;
        retryCount += 1;
        retryReasons.push('INVALID_OUTPUT');
        logAiEvent({
          eventType: AI_EVENT_TYPES.INVALID_OUTPUT,
          status: 'invalid',
          traceId: ctx.traceId,
          requestId: ctx.requestId,
          jobId: ctx.jobId,
          retryCount,
          retryReason: 'INVALID_OUTPUT',
          isProduction: config.environment === 'production',
          extra: {
            validationErrors: validation.errors.slice(0, 8),
            ...(config.debugLogRawResponse ? { rawResponsePreview: rawText } : {}),
          },
        });
        if (attempt + 1 < config.maxGenerationAttempts) {
          logAiEvent({
            eventType: AI_EVENT_TYPES.RETRY_TRIGGERED,
            status: 'retry',
            traceId: ctx.traceId,
            requestId: ctx.requestId,
            jobId: ctx.jobId,
            retryCount,
            retryReason: 'INVALID_OUTPUT',
            isProduction: config.environment === 'production',
          });
        }
        // eslint-disable-next-line no-await-in-loop
        await new Promise((r) => {
          setTimeout(r, Math.min(config.retryMaxMs, config.retryBaseMs * 2 ** attempt));
        });
        continue;
      }

      const seen = new Set(merged.map((m) => m.text.toLowerCase()));
      for (const row of validation.subjects) {
        const key = row.text.toLowerCase();
        if (seen.has(key)) continue;
        seen.add(key);
        merged.push(row);
      }
      if (merged.length >= config.expectedSubjectCount) {
        break;
      }
    } catch (e) {
      retryCount += 1;
      const code = e && typeof e === 'object' && 'code' in e ? String(e.code) : 'PARSE_ERROR';
      retryReasons.push(code);
      logAiEvent({
        eventType: AI_EVENT_TYPES.INVALID_OUTPUT,
        status: 'invalid',
        traceId: ctx.traceId,
        requestId: ctx.requestId,
        jobId: ctx.jobId,
        retryCount,
        retryReason: code,
        isProduction: config.environment === 'production',
        extra: config.debugLogRawResponse && rawText ? { rawResponsePreview: rawText } : {},
      });
      if (attempt + 1 < config.maxGenerationAttempts) {
        logAiEvent({
          eventType: AI_EVENT_TYPES.RETRY_TRIGGERED,
          status: 'retry',
          traceId: ctx.traceId,
          requestId: ctx.requestId,
          jobId: ctx.jobId,
          retryCount,
          retryReason: code,
          isProduction: config.environment === 'production',
        });
      }
      // eslint-disable-next-line no-await-in-loop
      await new Promise((r) => {
        setTimeout(r, Math.min(config.retryMaxMs, config.retryBaseMs * 2 ** attempt));
      });
    }
  }

  if (input.mode === 'brief') {
    const tone = input.tone;
    const effectiveBrief = input.effectiveBrief;
    const fallback = buildFallbackSubjectLines(effectiveBrief, tone);
    if (merged.length < config.expectedSubjectCount) {
      usedFallback = true;
      logAiEvent({
        eventType: AI_EVENT_TYPES.FALLBACK_USED,
        status: 'ok',
        traceId: ctx.traceId,
        requestId: ctx.requestId,
        jobId: ctx.jobId,
        isProduction: config.environment === 'production',
        extra: { reasons: retryReasons.slice(-3), validationErrors: lastInvalidReasons.slice(0, 4) },
      });
    }
    const legacy = subjectsToLegacyRows(merged);
    const finalLegacy = ensureExactlyFive(legacy, fallback);
    const subjects = finalLegacy.map((row) => ({
      text: row.subject,
      score: Math.min(1, Math.max(0, row.score / 10)),
    }));

    logAiEvent({
      eventType: AI_EVENT_TYPES.GENERATION_COMPLETED,
      status: 'ok',
      traceId: ctx.traceId,
      requestId: ctx.requestId,
      jobId: ctx.jobId,
      provider: 'http',
      processingTimeMs: Date.now() - started,
      retryCount,
      isProduction: config.environment === 'production',
      extra: { usedFallback, count: finalLegacy.length },
    });

    if (hooks?.persistLog) {
      await hooks.persistLog({
        event_type: AI_EVENT_TYPES.GENERATION_COMPLETED,
        status: 'SUCCESS',
        trace_id: ctx.traceId,
        request_id: ctx.requestId,
        job_id: ctx.jobId,
        user_id: ctx.userId,
        organization_id: ctx.organizationId,
        campaign_id: ctx.campaignId,
        provider: 'http',
        retry_count: retryCount,
        retry_reason: retryReasons.join(';') || null,
        processing_time_ms: Date.now() - started,
        is_fallback_used: usedFallback,
        environment: config.environment,
      });
    }

    return {
      subjects,
      subjectLines: finalLegacy,
      meta: { usedFallback, retryCount, processingTimeMs: Date.now() - started },
    };
  }

  // pipeline mode: expect exactly 5 from model or stub; still pad with fallback if needed
  const tone = 'professional';
  const effectiveBrief = buildEffectiveBrief({
    brief: String(input.ctx?.company ?? 'pipeline'),
    industry: String(input.ctx?.industry ?? ''),
    targetRole: String(input.ctx?.designation ?? ''),
    country: String(input.ctx?.country ?? ''),
  });
  const fallback = buildFallbackSubjectLines(effectiveBrief, tone);
  const legacy = subjectsToLegacyRows(merged);
  const finalLegacy = ensureExactlyFive(legacy, fallback);
  if (merged.length < config.expectedSubjectCount) {
    usedFallback = true;
    logAiEvent({
      eventType: AI_EVENT_TYPES.FALLBACK_USED,
      status: 'ok',
      traceId: ctx.traceId,
      requestId: ctx.requestId,
      jobId: ctx.jobId,
      isProduction: config.environment === 'production',
    });
  }
  const subjects = finalLegacy.map((row) => ({
    text: row.subject,
    score: Math.min(1, Math.max(0, row.score / 10)),
  }));

  logAiEvent({
    eventType: AI_EVENT_TYPES.GENERATION_COMPLETED,
    status: 'ok',
    traceId: ctx.traceId,
    requestId: ctx.requestId,
    jobId: ctx.jobId,
    provider: 'http',
    processingTimeMs: Date.now() - started,
    retryCount,
    isProduction: config.environment === 'production',
    extra: { usedFallback, mode: 'pipeline' },
  });

  if (hooks?.persistLog) {
    await hooks.persistLog({
      event_type: AI_EVENT_TYPES.GENERATION_COMPLETED,
      status: 'SUCCESS',
      trace_id: ctx.traceId,
      request_id: ctx.requestId,
      job_id: ctx.jobId,
      user_id: ctx.userId,
      organization_id: ctx.organizationId,
      campaign_id: ctx.campaignId,
      retry_count: retryCount,
      processing_time_ms: Date.now() - started,
      is_fallback_used: usedFallback,
      environment: config.environment,
    });
  }

  return {
    subjects,
    subjectLines: finalLegacy,
    meta: { usedFallback, retryCount, processingTimeMs: Date.now() - started },
  };
}

module.exports = {
  runSubjectLineGeneration,
  subjectsToLegacyRows,
};
