/** @readonly */
const AI_EVENT_TYPES = Object.freeze({
  REQUEST_RECEIVED: 'REQUEST_RECEIVED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  GENERATION_STARTED: 'GENERATION_STARTED',
  GENERATION_COMPLETED: 'GENERATION_COMPLETED',
  GENERATION_FAILED: 'GENERATION_FAILED',
  RETRY_TRIGGERED: 'RETRY_TRIGGERED',
  TIMEOUT_OCCURRED: 'TIMEOUT_OCCURRED',
  INVALID_OUTPUT: 'INVALID_OUTPUT',
  FALLBACK_USED: 'FALLBACK_USED',
  PARTIAL_FAILURE: 'PARTIAL_FAILURE',
  BATCH_COMPLETED: 'BATCH_COMPLETED',
});

module.exports = { AI_EVENT_TYPES };
