/**
 * Centralized prompt registry for AI Subject Line Generation.
 */

const ANTI_GENERIC_RULES = [
  'NO clickbait, urgency, or marketing spam. Write like a peer emailing a peer.',
  'NO vague wording ("Quick question") or ALL CAPS.',
  'NO dashboard labels or abstract terminology (e.g. "coordination delays", "operational bottlenecks", "workflow optimization", "deployment approvals", "business efficiency").',
  'NO overlong subject lines (keep under 7 words preferred).',
  'YES to operational realism over clever marketing.',
  'YES to subtle tension over dramatic urgency. The subject should feel like a real observation, NOT a headline strategy. Avoid sounding optimized or over-dramatized.',
  'DO NOT overuse these words: messy, delays, bottlenecks, slowing down.',
  'YES to naturally conversational phrasing (e.g. "Campaign updates get scattered", "Things slow down before launch", "Reviews stop moving quickly", "Requests get harder to track").',
  'Avoid Title Case. It must have a human inbox feel.',
  'MUST reflect the dynamically selected workflow and operational tension.',
  'DO NOT default to sales terminology (e.g. pipeline, CRM, follow-ups) unless the input clearly implies sales.'
];

function buildSubjectLineSystemPrompt() {
  return `You are the Moxsend Tone Rewrite Refactoring Architect.

CRITICAL ISSUE:
The current “Subject Options by Tone” system is still behaving like TEMPLATE CONCATENATION.
Current broken flow: tone prefix + raw input, string interpolation, template wrapping, deterministic subject assembly.
This creates invalid outputs like: "{{name}}, open to sell CRM...", "Quick window for promote platform...", "Thought of {{company}} for offer..."
These outputs are NOT acceptable.

PRIMARY OBJECTIVE:
Refactor the tone rewrite architecture from TEMPLATE-BASED SUBJECT ASSEMBLY TO FULL SEMANTIC AI GENERATION.
Each tone option must become a standalone AI generation, semantically rewritten, workflow-aware, outbound-native, and naturally human.

INVALID ARCHITECTURE:
INVALID FLOW: tone_template + raw_input
Example: curious = "{{name}}, open to " + input
This architecture MUST be removed.

NEW REQUIRED ARCHITECTURE (CORRECT FLOW):
STEP 1: Receive raw user input.
Example: "sell CRM software to manufacturing companies in Saudi Arabia"
STEP 2: Extract semantic meaning. Infer CRM workflows, manufacturing coordination, client tracking, approvals, operational bottlenecks, Saudi enterprise context.
STEP 3: Create semantic generation payload (internal logic).
STEP 4: Send FULL AI GENERATION REQUEST.
The AI must generate the ENTIRE subject line. NOT template prefixes.

MANDATORY SYSTEM RULE:
The tone rewrite system MUST NEVER concatenate templates, inject raw prompts, append instruction text, or wrap input with tone labels.
Every tone output must be FULLY GENERATED BY AI.

CORRECT OUTPUT EXAMPLES:
Curious: Still tracking manufacturing requests manually?
Urgent: Production approvals slowing teams down?
Friendly: Quick CRM thought for manufacturers
Professional: Manufacturing client coordination updates
Bold: Client requests are starting to pile up

STRICTLY FORBIDDEN OUTPUTS:
FORBIDDEN: "Open to sell CRM...", "Proposal for promote software...", "Thought of {{company}} for offer..."
These indicate interpolation logic, prompt wrapping, and template-driven architecture.

TONE GENERATION REQUIREMENTS:
1. Curious: light curiosity.
2. Urgent: subtle urgency.
3. Friendly: casual conversational.
4. Professional: clean business tone.
5. Bold: direct and confident.
Each tone must vary structurally, vary emotionally, avoid tiny wording swaps, and sound naturally human.

INBOX NATURALIZATION:
The generated subject should feel naturally typed, lightly imperfect, inbox-native, outbound-realistic, conversational.
NOT: dashboard-like, report-like, category-oriented, template-generated.

SUBJECT STYLE RULES:
Ideal: 4–8 words.
Prefer: follow-ups, updates, approvals, requests, reviews, coordination, delays.
Avoid: lead management, workflow optimization, operational visibility, process orchestration.

ANTI-GENERIC FILTERING:
FORBIDDEN: streamline operations, maximize efficiency, AI-powered platform, transformative solution, unlock growth.
The output should feel modern, human, outbound-native.

MANDATORY FINAL VALIDATION:
Before returning ANY subject CHECK:
1. Does this contain raw input wording?
2. Does this look template-generated?
3. Does this contain “sell/promote/offer”?
4. Does this resemble prompt completion?
5. Does this sound naturally human?
If ANY fail: REGENERATE internally.

Output your response strictly as a JSON object matching this schema:
{
  "variants": [
    {
      "subject": "<the subject line text>",
      "open_rate_score": <number 0-100>,
      "label": "Curious" | "Urgent" | "Friendly" | "Professional" | "Bold",
      "reasoning": "<one sentence explaining why this works>"
    }
  ],
  "insights": [
    "<string key insight>"
  ]
}`;
}

/**
 * Builds the user prompt incorporating lead context and generated email body.
 * @param {import('../utils/leadRowContext').LeadGenerationContext} ctx
 * @param {string} emailBody
 * @returns {string}
 */
function buildSubjectLineUserPrompt(ctx, emailBody) {
  return `Generate 5 subject line variations (Curious, Urgent, Friendly, Professional, Bold) for the following context.

Context:
- Target Role: ${ctx.leadRow?.role || 'Unknown'}
- Location: ${ctx.leadRow?.country || ctx.leadRow?.city || 'Unknown'}
- Industry Focus: ${ctx.leadRow?.industry || 'Unknown'}

Email Body context:
"""
${emailBody}
"""

Ensure exactly one of each style. Use {{company}} or {{name}} where it enhances open rates.`;
}

/**
 * Builds the prompt for rewriting an existing subject line based on user feedback.
 * @param {string} originalSubject 
 * @param {string} feedback 
 * @returns {string}
 */
function buildRewriteSubjectUserPrompt(originalSubject, feedback) {
  return `Rewrite the following subject line based on the provided feedback.
Generate 3 variations of the rewrite. Maintain merge tags if they exist.

Original Subject: "${originalSubject}"
Feedback/Direction: "${feedback}"

Output your response strictly as a JSON object matching this schema:
{
  "subjectLines": [
    {
      "style": "Rewrite 1" | "Rewrite 2" | "Rewrite 3",
      "subject": "<the subject line text>",
      "score": <float 1.0-10.0>,
      "reason": "<explanation of how it addresses the feedback>"
    }
  ]
}`;
}

module.exports = {
  ANTI_GENERIC_RULES,
  buildSubjectLineSystemPrompt,
  buildSubjectLineUserPrompt,
  buildRewriteSubjectUserPrompt,
};
