const INJECTION_PATTERNS = [/ignore previous/gi, /system prompt/gi, /act as/gi];

function sanitizeInput(value) {
  let cleaned = String(value ?? '')
    .replace(/[\u0000-\u001F\u007F]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  for (const pattern of INJECTION_PATTERNS) cleaned = cleaned.replace(pattern, '');
  return cleaned.replace(/\s+/g, ' ').trim();
}

function clampScore(value) {
  const n = typeof value === 'number' ? value : Number(value);
  if (!Number.isFinite(n)) return 5;
  return Math.min(10, Math.max(1, Math.round(n)));
}

function normalizeSubjectLines(raw) {
  const source = Array.isArray(raw) ? raw : [];
  const seen = new Set();
  const out = [];
  for (const item of source) {
    if (!item || typeof item !== 'object') continue;
    const subject = String(item.subject ?? '').trim();
    if (!subject) continue;
    const key = subject.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({
      style: String(item.style ?? 'General').trim() || 'General',
      subject,
      score: clampScore(item.score),
      reason: String(item.reason ?? 'Generated by AI').trim() || 'Generated by AI',
    });
  }
  return out;
}

function buildFallbackSubjectLines(brief, tone) {
  const shortBrief = sanitizeInput(brief).slice(0, 60) || 'your goals';
  return [
    { style: 'Curiosity', subject: `Quick thought on ${shortBrief}`, score: 6, reason: `Fallback (${tone})` },
    { style: 'Urgency', subject: `Time-sensitive idea for ${shortBrief}`, score: 6, reason: `Fallback (${tone})` },
    { style: 'Benefit', subject: `A practical way to improve ${shortBrief}`, score: 6, reason: `Fallback (${tone})` },
    { style: 'Personalised', subject: `${shortBrief} for your team`, score: 6, reason: `Fallback (${tone})` },
    { style: 'Question-based', subject: `Open to improving ${shortBrief}?`, score: 6, reason: `Fallback (${tone})` },
  ];
}

function ensureExactlyFive(items, fallbackItems) {
  const out = [...items];
  const seen = new Set(out.map((s) => s.subject.toLowerCase()));
  for (const fallback of fallbackItems) {
    if (out.length >= 5) break;
    const key = fallback.subject.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(fallback);
  }
  return out.slice(0, 5);
}

function buildEffectiveBrief({ brief, industry, targetRole, country }) {
  const parts = [
    sanitizeInput(brief),
    industry ? `Industry: ${sanitizeInput(industry)}` : '',
    targetRole ? `Target role: ${sanitizeInput(targetRole)}` : '',
    country ? `Country: ${sanitizeInput(country)}` : '',
  ].filter(Boolean);
  return parts.join('. ');
}

module.exports = {
  INJECTION_PATTERNS,
  sanitizeInput,
  clampScore,
  normalizeSubjectLines,
  buildFallbackSubjectLines,
  ensureExactlyFive,
  buildEffectiveBrief,
};
