"""
LangGraph Node: generate_subjects

Calls Qwen (via ChatOllama) to generate exactly 5 subject line variations
for a single lead. Each variation covers a distinct tone/style.

Retry logic: if the model returns malformed JSON, we retry once with a
stricter prompt before falling back to safe defaults.
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any

from moxsend_graph.states.subject_state import SubjectGraphState, SubjectLineEntry
from llm_handler.llm_handler import llm

logger = logging.getLogger(__name__)

MODEL_NAME = "qwen2.5:7b"

STYLES = ['Curiosity', 'Urgency', 'Benefit', 'Personalised', 'Question-based']

# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """You are an expert email copywriter.
Return ONLY valid JSON with this shape:
{ "subjectLines": [{ "style": "Curiosity", "subject": "...", "score": 8, "reason": "..." }] }
No markdown. No commentary."""

def _build_user_prompt(lead: dict[str, Any]) -> str:
    tone = str(lead.get("tags", "")).strip() or "Professional"
    
    brief_raw = str(lead.get("notes", "")).strip()
    industry = str(lead.get("industry", "")).strip()
    role = str(lead.get("designation", "")).strip()
    country = str(lead.get("country", "")).strip()
    
    parts = [brief_raw] if brief_raw else []
    if industry:
        parts.append(f"Industry: {industry}")
    if role:
        parts.append(f"Target role: {role}")
    if country:
        parts.append(f"Country: {country}")
        
    brief = ". ".join(filter(None, parts))
    if not brief:
        brief = "business improvement"

    return f"""Generate exactly 5 high-performing email subject lines.
Tone: {tone}
Brief: {brief}
Styles to include: {', '.join(STYLES)}"""


# ---------------------------------------------------------------------------
# JSON extraction helpers
# ---------------------------------------------------------------------------

def _extract_json_block(text: str) -> str:
    """Extract the first {...} block from potentially noisy LLM output."""
    # Try to find a JSON block directly
    match = re.search(r'\{[\s\S]*\}', text)
    if match:
        return match.group(0)
    return text


def _parse_subjects(raw_text: str) -> list[dict[str, Any]]:
    """
    Parse the LLM response into a list of subject dicts.
    Raises ValueError on failure so the caller can retry.
    """
    cleaned = _extract_json_block(raw_text.strip())
    data = json.loads(cleaned)

    if not isinstance(data, dict):
        raise ValueError(f"Expected dict, got {type(data)}")

    subjects = data.get("subjects") or data.get("subjectLines") or data.get("variants")
    if not isinstance(subjects, list):
        raise ValueError("No 'subjects' array found in response")

    validated: list[dict[str, Any]] = []
    for item in subjects:
        if not isinstance(item, dict):
            continue
        subject_text = str(item.get("subject") or item.get("text") or "").strip()
        if not subject_text:
            continue
        style = str(item.get("style") or item.get("label") or "General").strip()
        try:
            score = float(item.get("score") or item.get("open_rate_score") or 7.0)
        except (TypeError, ValueError):
            score = 7.0
        score = max(1.0, min(10.0, score))
        reason = str(item.get("reason") or item.get("reasoning") or "Generated by AI").strip()
        validated.append({"subject": subject_text, "style": style, "score": score, "reason": reason})

    if not validated:
        raise ValueError("Parsed subjects list is empty")

    return validated


# ---------------------------------------------------------------------------
# Fallback subject lines (used if both attempts fail)
# ---------------------------------------------------------------------------

def _build_fallback_subjects(lead: dict[str, Any]) -> list[dict[str, Any]]:
    company = str(lead.get("company", "")).strip() or "your team"
    industry = str(lead.get("industry", "")).strip() or "your industry"
    designation = str(lead.get("designation", "")).strip() or "professionals"

    return [
        {
            "style": "Curious",
            "subject": f"How {company} handles team coordination",
            "score": 6.0,
            "reason": "Fallback — piques curiosity about internal process",
        },
        {
            "style": "Urgent",
            "subject": f"A quick gap I noticed in {industry}",
            "score": 6.0,
            "reason": "Fallback — creates mild urgency",
        },
        {
            "style": "Friendly",
            "subject": f"Thought this might be useful for {company}",
            "score": 6.0,
            "reason": "Fallback — casual and non-intrusive",
        },
        {
            "style": "Professional",
            "subject": f"{industry} coordination — worth a conversation?",
            "score": 6.0,
            "reason": "Fallback — clean professional tone",
        },
        {
            "style": "Bold",
            "subject": f"What {designation}s usually miss",
            "score": 6.0,
            "reason": "Fallback — direct and confident",
        },
    ]


# ---------------------------------------------------------------------------
# LangGraph node
# ---------------------------------------------------------------------------

def generate_subjects_node(state: SubjectGraphState) -> dict:
    """
    Generate subjects using the model router.
    """
    lead = state.get("lead", {})
    prompt = f"{SYSTEM_PROMPT}\n\n{_build_user_prompt(lead)}"

    # --- Attempt 1 ---
    try:
        text = llm.generate_json(prompt)
        subjects = _parse_subjects(text)
        logger.info(
            "generate_subjects_node: parsed %d subjects for lead %s (attempt 1)",
            len(subjects),
            lead.get("email", "unknown"),
        )
        return {"raw_subjects": subjects}
    except Exception as exc:
        logger.warning(
            "generate_subjects_node: attempt 1 failed for %s: %s",
            lead.get("email", "unknown"),
            exc,
        )

    # --- Attempt 2: stricter prompt ---
    strict_user = (
        _build_user_prompt(lead)
        + "\n\nCRITICAL: Return ONLY the raw JSON object. No markdown. No explanation. No code fences."
    )
    try:
        text2 = llm.generate_json(f"{SYSTEM_PROMPT}\n\n{strict_user}")
        subjects2 = _parse_subjects(text2)
        logger.info(
            "generate_subjects_node: parsed %d subjects for lead %s (attempt 2)",
            len(subjects2),
            lead.get("email", "unknown"),
        )
        return {"raw_subjects": subjects2}
    except Exception as exc2:
        logger.error(
            "generate_subjects_node: both attempts failed for %s: %s — using fallback",
            lead.get("email", "unknown"),
            exc2,
        )
        fallback = _build_fallback_subjects(lead)
        return {
            "raw_subjects": fallback,
            "error": f"Generation failed: {exc2}; fallback used.",
        }
