import json
import logging
import re
from typing import Any
from llm_handler.llm_handler import llm
from moxsend_graph.states.email_state import EmailState

logger = logging.getLogger(__name__)

STYLES = ['Curiosity', 'Urgency', 'Benefit', 'Personalised', 'Question-based']

SYSTEM_PROMPT = """You are an expert email copywriter.
Return ONLY valid JSON with this shape:
{ "subjects": [{ "style": "BEST OVERALL", "subject": "..", "score": .., "reason": ".." }] }
No markdown. No commentary."""

def generate_subject_lines_node(state: EmailState) -> dict:
    body = state.get("generated_base_email", "")
    tone = state.get("tone", "Professional")
    
    user_prompt = f"""Generate exactly 1 high-performing email subject lines based on this email body. B2B Coverting subject lines for the business.
Tone: {tone}
Styles to include: {', '.join(STYLES)}

Email Body:
{body}"""
    
    try:
        prompt = f"{SYSTEM_PROMPT}\n\n{user_prompt}"
        model = state.get("model")
        text = llm.generate_json(prompt, provider_name=model)

        match = re.search(r'\{[\s\S]*\}', text)
        cleaned = match.group(0) if match else text
        data = json.loads(cleaned)
        
        subjects = data.get("subjects") or data.get("subjectLines") or data.get("variants") or []
        validated = []
        
        for item in subjects:
            if not isinstance(item, dict): continue
            subj = str(item.get("subject", item.get("text", ""))).strip()
            if not subj: continue
            
            style = str(item.get("style", "General")).strip()
            try:
                score = float(item.get("score", 7.0))
            except:
                score = 7.0
            
            reason = str(item.get("reason", "Generated by AI")).strip()
            validated.append({"subject": subj, "style": style, "score": score, "reason": reason})
            
        if not validated:
            raise ValueError("No valid subjects parsed")
    

        return {"generated_subject_lines": validated[:1]}
    except Exception as e:
        logger.exception("Failed to generate cohort subjects")
        raise RuntimeError(f"Failed to generate cohort subjects: {e}") from e
