"""
LangGraph Node: score_subjects

Uses model router for scoring.
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any


from moxsend_graph.states.subject_state import SubjectGraphState, SubjectLineEntry
from llm_handler.llm_handler import llm

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Scoring prompt
# ---------------------------------------------------------------------------

SCORING_SYSTEM = """You are an email open-rate expert.

You will receive a list of cold email subject lines and the lead context they were written for.
Your job is to score each subject line on a scale of 1.0 to 10.0 for cold email open-rate likelihood.

Scoring criteria:
- Specificity to the lead's role/industry/company (+)
- Natural inbox feel, not marketing-speak (+)
- Appropriate length (4-8 words ideal) (+)
- Generic phrasing or buzzwords (-)
- All-caps, clickbait, or manipulation (-)

OUTPUT FORMAT — respond with ONLY valid JSON, no markdown:
{
  "scores": [
    {"subject": "<exact subject text>", "score": <float 1.0-10.0>, "reason": "<one sentence>"},
    ...
  ]
}"""


def _build_scoring_prompt(lead: dict[str, Any], subjects: list[dict[str, Any]]) -> str:
    company = str(lead.get("company", "")).strip() or "unknown company"
    designation = str(lead.get("designation", "")).strip() or "professional"
    industry = str(lead.get("industry", "")).strip() or "business"
    country = str(lead.get("country", "")).strip() or "unknown region"

    subjects_text = "\n".join(
        f'{i + 1}. [{s["style"]}] "{s["subject"]}"'
        for i, s in enumerate(subjects)
    )

    return (
        f"Lead context:\n"
        f"  Company: {company}\n"
        f"  Role: {designation}\n"
        f"  Industry: {industry}\n"
        f"  Country: {country}\n\n"
        f"Subject lines to score:\n{subjects_text}\n\n"
        "Return ONLY the JSON object with scores as described in the system prompt."
    )


# ---------------------------------------------------------------------------
# Parse scoring response
# ---------------------------------------------------------------------------

def _extract_json_block(text: str) -> str:
    match = re.search(r'\{[\s\S]*\}', text)
    if match:
        return match.group(0)
    return text


def _merge_scores(
    original: list[dict[str, Any]],
    scoring_response: str,
) -> list[SubjectLineEntry]:
    """
    Merge LLM scores into the original subjects list.
    Matched by subject text (case-insensitive).
    Falls back to original generation scores for unmatched items.
    """
    cleaned = _extract_json_block(scoring_response.strip())
    data = json.loads(cleaned)
    score_list: list[dict[str, Any]] = data.get("scores", [])

    score_map: dict[str, float] = {}
    reason_map: dict[str, str] = {}
    for item in score_list:
        key = str(item.get("subject", "")).strip().lower()
        if key:
            try:
                score_map[key] = max(1.0, min(10.0, float(item.get("score", 7.0))))
            except (TypeError, ValueError):
                pass
            reason_map[key] = str(item.get("reason", "")).strip()

    merged: list[SubjectLineEntry] = []
    for s in original:
        subject_text = str(s.get("subject", "")).strip()
        key = subject_text.lower()
        score = score_map.get(key, float(s.get("score", 7.0)))
        reason = reason_map.get(key) or str(s.get("reason", "Generated by AI")).strip()
        merged.append(
            SubjectLineEntry(
                subject=subject_text,
                style=str(s.get("style", "General")).strip(),
                score=round(score, 1),
                reason=reason,
            )
        )
    return merged


def _to_subject_entries(raw: list[dict[str, Any]]) -> list[SubjectLineEntry]:
    """Convert raw dicts to typed SubjectLineEntry without scoring pass."""
    result: list[SubjectLineEntry] = []
    for s in raw:
        try:
            score = max(1.0, min(10.0, float(s.get("score", 7.0))))
        except (TypeError, ValueError):
            score = 7.0
        result.append(
            SubjectLineEntry(
                subject=str(s.get("subject", "")).strip(),
                style=str(s.get("style", "General")).strip(),
                score=round(score, 1),
                reason=str(s.get("reason", "Generated by AI")).strip(),
            )
        )
    return result


# ---------------------------------------------------------------------------
# LangGraph node
# ---------------------------------------------------------------------------

def score_subjects_node(state: SubjectGraphState) -> dict:
    """
    Score subjects using model router.
    """
    lead = state.get("lead", {})
    raw_subjects = state.get("raw_subjects", [])
    workflow_id = state.get("metadata", {}).get("workflow_id", "")
    lead_id = state.get("lead_id", "")

    if not raw_subjects:
        logger.warning("score_subjects_node: no raw_subjects in state, skipping scoring.")
        return {
            "scored_subjects": [],
            "best_subject": SubjectLineEntry(
                subject="No subject lines available",
                style="General",
                score=1.0,
                reason="Generation produced no output",
            ),
        }


    # --- Attempt scoring via LLM ---
    try:
        user_prompt = _build_scoring_prompt(lead, raw_subjects)
        prompt = f"{SCORING_SYSTEM}\n\n{user_prompt}"
        scored = _merge_scores(raw_subjects, llm.generate_json(prompt))
        logger.info(
            "score_subjects_node: scored %d subjects for lead %s",
            len(scored),
            lead.get("email", "unknown"),
        )
    except Exception as exc:
        logger.warning(
            "score_subjects_node: scoring failed for %s: %s — using generation scores",
            lead.get("email", "unknown"),
            exc,
        )
        scored = _to_subject_entries(raw_subjects)

    # --- Ensure we have exactly 5 entries (pad with original scores if needed) ---
    if len(scored) < len(raw_subjects):
        existing_subjects = {e["subject"].lower() for e in scored}
        for s in raw_subjects:
            if s["subject"].lower() not in existing_subjects:
                try:
                    score = max(1.0, min(10.0, float(s.get("score", 7.0))))
                except (TypeError, ValueError):
                    score = 7.0
                scored.append(
                    SubjectLineEntry(
                        subject=str(s.get("subject", "")).strip(),
                        style=str(s.get("style", "General")).strip(),
                        score=round(score, 1),
                        reason=str(s.get("reason", "Generated by AI")).strip(),
                    )
                )

    # --- Pick best ---
    best = max(scored, key=lambda x: x["score"])

    return {
        "scored_subjects": scored,
        "best_subject": best,
    }
